ALTER TABLE "public"."jarvis_transactions"
ADD COLUMN IF NOT EXISTS "notes" TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS "tax_relevant" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "tags" JSONB NOT NULL DEFAULT '[]'::jsonb;
